# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rtruncnorm <- function(mu, sigma, a, b) {
    .Call(`_farva_rtruncnorm`, mu, sigma, a, b)
}

rmvnrnd <- function(mu, Sigma, n) {
    .Call(`_farva_rmvnrnd`, mu, Sigma, n)
}

rnormArma <- function(mu, sig_sq) {
    .Call(`_farva_rnormArma`, mu, sig_sq)
}

get_Omega_i <- function(Theta_c, xi_i) {
    .Call(`_farva_get_Omega_i`, Theta_c, xi_i)
}

sample_xi_all <- function(num_causes, L, K, N, beta_c_all, X_all_sig, Sigma_0_vec, Theta_all, xi_all, z_all, eta_all) {
    .Call(`_farva_sample_xi_all`, num_causes, L, K, N, beta_c_all, X_all_sig, Sigma_0_vec, Theta_all, xi_all, z_all, eta_all)
}

sample_psi_i <- function(SigPsi, alpha_c, X_i, Sigma_0_vec, Omega_i, z_i) {
    .Call(`_farva_sample_psi_i`, SigPsi, alpha_c, X_i, Sigma_0_vec, Omega_i, z_i)
}

sample_Theta_j <- function(sig_sq_j, xi_c, eta_c, z_cj, Delta_j, phi_j, tau) {
    .Call(`_farva_sample_Theta_j`, sig_sq_j, xi_c, eta_c, z_cj, Delta_j, phi_j, tau)
}

sample_Theta_j_noobs <- function(Delta_j, phi_j, tau) {
    .Call(`_farva_sample_Theta_j_noobs`, Delta_j, phi_j, tau)
}

sample_Delta_jl <- function(phi_jl_delta, tau_l_delta, Theta_jl, phi_jl_theta, tau_l_theta) {
    .Call(`_farva_sample_Delta_jl`, phi_jl_delta, tau_l_delta, Theta_jl, phi_jl_theta, tau_l_theta)
}

sample_nu <- function(xi_i, Theta_c, Sigma_0, z_i, psi_i) {
    .Call(`_farva_sample_nu`, xi_i, Theta_c, Sigma_0, z_i, psi_i)
}

sample_phi_pl <- function(nu, tau_deltaSq, C) {
    .Call(`_farva_sample_phi_pl`, nu, tau_deltaSq, C)
}

sample_delta_theta <- function(a1, a2, Delta, Theta, phi_theta, delta_theta, h) {
    .Call(`_farva_sample_delta_theta`, a1, a2, Delta, Theta, phi_theta, delta_theta, h)
}

sample_delta_Delta <- function(a1, a2, Delta, phi_delta, delta_delta, h) {
    .Call(`_farva_sample_delta_Delta`, a1, a2, Delta, phi_delta, delta_delta, h)
}

sample_beta_c <- function(y, mu_beta, Sigma_beta, sig_sq, XtX, Xt) {
    .Call(`_farva_sample_beta_c`, y, mu_beta, Sigma_beta, sig_sq, XtX, Xt)
}

sample_beta_c_noobs <- function(mu_beta, Sigma_beta) {
    .Call(`_farva_sample_beta_c_noobs`, mu_beta, Sigma_beta)
}

sample_betaxi_c <- function(z_c, Sig0vec, eta_c, Theta_c, beta_c, mu_beta, Sigma_beta, XXt_c, X_c, k_get, l_get, is_obs) {
    .Call(`_farva_sample_betaxi_c`, z_c, Sig0vec, eta_c, Theta_c, beta_c, mu_beta, Sigma_beta, XXt_c, X_c, k_get, l_get, is_obs)
}

sample_beta_mu <- function(mu_0, Lambda_0, C, beta_mean, Sigma_beta) {
    .Call(`_farva_sample_beta_mu`, mu_0, Lambda_0, C, beta_mean, Sigma_beta)
}

sample_beta_Sigma <- function(v0, S0, C, beta_mu, beta_c) {
    .Call(`_farva_sample_beta_Sigma`, v0, S0, C, beta_mu, beta_c)
}

sample_sigsq <- function(a, b, n, RSS) {
    .Call(`_farva_sample_sigsq`, a, b, n, RSS)
}

sample_xi_istar <- function(beta_c, X_istar) {
    .Call(`_farva_sample_xi_istar`, beta_c, X_istar)
}

sample_psi_istar <- function(sig_sq_psi, alpha_c, X_istar, fix_psi) {
    .Call(`_farva_sample_psi_istar`, sig_sq_psi, alpha_c, X_istar, fix_psi)
}

sample_z_mean_cov_all <- function(S_mat, Omega_all, eta_all, N, Sig0vec, z_all_nominus, z_all, P, is_binary, mu_all, mu_collapse, psi_all) {
    .Call(`_farva_sample_z_mean_cov_all`, S_mat, Omega_all, eta_all, N, Sig0vec, z_all_nominus, z_all, P, is_binary, mu_all, mu_collapse, psi_all)
}

get_piSgivenY <- function(N_test, num_causes, P, mc_tot, cov_incl, X_test_mu, X_test_sig, S_test, beta_c_all, Theta_all, mu_collapse, gamma_c_all, alpha_c_all, sigSqpsi_all, Sigma_0, is_binary) {
    .Call(`_farva_get_piSgivenY`, N_test, num_causes, P, mc_tot, cov_incl, X_test_mu, X_test_sig, S_test, beta_c_all, Theta_all, mu_collapse, gamma_c_all, alpha_c_all, sigSqpsi_all, Sigma_0, is_binary)
}

